### ISSUE TITLE
About PREGENERATED DATABASE

### ISSUE THREAD

**Issue by wxyyyyyx** [mobiusklein/glycresoft#11]
Hi Joshua,
I am using your Glycresoft software to analyze the mass spectrum of the glycosaminoglycan standard. When establishing the database, I encountered some problems about the Pregenerated database.
Can the Pregenerated Database in your program be directly used to analyze the glycosaminoglycan extracted from Marine shellfish?
![image](https://user-images.githubusercontent.com/84690225/119283321-34e8dd00-bc6f-11eb-8c32-6fbb12859200.png)

If not, please help me to look at my own database is this correct?
![image](https://user-images.githubusercontent.com/84690225/119283292-1da9ef80-bc6f-11eb-8369-192e91f0c52c.png)

Thank you very much for your help!
Thank you very much!

**Comment by mobiusklein** [comment]
I know nothing about the glycosaminoglycans (GAGs) from shellfish, so I can't say whether it is biologically appropriate, but the pre-generated database is similar to the rules you list for yourself. Note that you still need to specify any derivatization or reduction steps you applied yourself.

The prebuilt glycan database "Low Molecular Weight Heparins" is functionally equivalent to a combinatorial glycan hypothesis with the following ranges:
```
HexA 1-9
HexN 1-9
enHexA 0-1
@acetyl 0-9
@sulfate 0-48
```
and constraints:
```
@acetyl <=  HexN
@sulfate <= ((HexN * 3 - @acetyl) + (HexA * 2) + (enHexA * 2))
HexA <= HexN + 1
HexN <= HexA + 1
```
This ends up being a relatively large combinatorial space of over 6,000 glycan compositions. `enHexA` is identical to `en,a-Hex`. The reason I only included one `enHexA` is because in the scenario I was working with, the glycosidase I was designing for cuts at `a-Hex` and leaves a "saturated"/double bond (en) behind. It is theoretically possible to have a molecule cut on both ends of the chain but it would just be chemical noise. There wouldn't be a good reason to have more than that many `enHexA`s in the chain unless you had done more chemical manipulation of the sample.

Your ranges would need to follow the same constraint expressions as mine or else you'd end up with unbalanced glycan compositions, e.g. a composition all of `a-Hex` with no `HexN`, which fails to follow the disaccharide pattern of glycosaminoglycans, or a chain with 9 acetyl groups on two monosaccharides.

You mentioned you had a problem with the pre-generated database. Did it throw an error during the building process, or did it fail to find matches to your data? Chances are that if it just failed to match anything it's more likely that the preprocessing algorithm didn't really understand your mass spectra. GlycReSoft was designed around high resolution mass spectra, and can work with FT and TOF detectors, having tested with Agilent, Thermo, and Bruker, but it may not behave well on ion trap data. Additionally, while glycans and glycopeptides to some extent can abide by an "average monomer" isotopic model, sulfated glycosaminoglycans _do not_. This means that isotopic pattern fitting method the preprocessing algorithm uses is more error-prone than normal on sulfated GAGs. You can check the chromatograms extracted by clicking on the sample run and exporting them to a CSV file and spot-check the most abundant ones, especially if you have a spiked in standard.

**Comment by wxyyyyyx** [comment]
Do you mean that I can use the Low Molecular Weight Heparin option in the pre-generated database to match my glycosaminoglycan sample?
If yes, I will try again. If not, I may have to trouble you to answer some of my questions.
Thanks again for your help! Thank you very much!

**Comment by mobiusklein** [comment]
In theory, yes, it should work for your problem. As I said, the pre-generated database looks very similar to the rules you laid out, differing primarily in the number of sulfates allowed and the restriction on `en,a-Hex` to be at most 1.

**Comment by wxyyyyyx** [comment]
Thank you for your generous help!I will continue to try, and hope to communicate with you if there is any problem!
Thanks again!

**Comment by wxyyyyyx** [comment]
Thank you for your generous help!I will continue to try, and hope to communicate with you if there is any problem!
Thanks again!
