### ISSUE TITLE
Hello, excuse me, I am using your software, I want to ask about the matching problem

### ISSUE THREAD

**Issue by wxyyyyyx** [mobiusklein/glycresoft#12]
According to your instructions before, I created the database and uploaded the samples in the corresponding format.When matching samples from the database, I found that the following Settings had a significant impact on the results,So I increased the fault tolerance accordingly,Is that justified?It would be better if you could help me explain the principle.
Thank you so much for your help! Thank you very much!
![image](https://user-images.githubusercontent.com/84690225/125395310-9b6fb900-e3dd-11eb-9afb-15778dadf4a2.png)

**Comment by wxyyyyyx** [comment]
![image](https://user-images.githubusercontent.com/84690225/125401201-70896300-e3e5-11eb-849d-e1b154510b69.png)
The last picture is the original value, and this is what I enlarged. Thank you!

**Comment by mobiusklein** [comment]
What kind of molecule are you attempting to interpret and what kind of mass spectrometer did you use? You modified the "Adduct Limit" parameter, did you specify any adducts in the input table on the right not shown in your screen captures?

GlycReSoft is designed to interpret high resolution glycan and glycopeptide mass spectra. The expected average mass accuracy on high resolution instruments is in the range of 5 to 40 parts-per-million mass accuracy (PPM). It also operates on deconvoluted mass spectra that have been processed by its deisotoping and charge state deconvolution algorithm, which requires isotopic patterns be detectable. It has been shown to work on both FT-MS (Orbitrap, FT-ICR) and TOF mass analyzers, but not on ion traps or other lower resolution devices.

The mass accuracy you selected allows for 2,000 PPM error, which means your results will be pretty noisy. This allows for an error of 0 .4 Da at 200 Da, or 2 Da at 1000 Da. This means that the mass difference between the thing your instrument measured and the thing in the glycan database can be large enough to make the assignment by intact mass alone questionable. The glycan search portion of GlycReSoft's UI doesn't include MSn interpretation filtering.

The peak grouping mass accuracy is used when constructing chromatograms, chaining peaks with similar masses from adjacent MS1 spectra together into a sequence over time. The quantity you use there should reflect the upper bound on the amount of intra-analyte variation you expect from your mass analyzer, and the default value of 15 PPM is already pretty generous for high resolution mass spectra. This parameter is important because it controls the fidelity of each extracted chromatogram which is what is ultimately evaluated when matched to a glycan.

**Comment by wxyyyyyx** [comment]
I see. What you mean is that the default PPM value is the most rigorous, so I will not change it easily.A thousand thanks for your generous help
